[package]
name = "helper"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rcore-fs = { git = "https://github.com/rcore-os/rcore-fs", rev = "6df6cd2" }